FROM python:3.10-slim

RUN apt-get update && apt-get install -y gettext && rm -rf /var/lib/apt/lists/*

RUN pip install \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres \
    dagster-docker

# Set $DAGSTER_HOME and copy dagster.yaml and workspace.yaml there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

WORKDIR $DAGSTER_HOME

COPY config/dagster.yaml.template config/workspace.yaml $DAGSTER_HOME
COPY config/entrypoint.sh $DAGSTER_HOME

RUN chmod +x $DAGSTER_HOME/entrypoint.sh
ENTRYPOINT ["sh", "/opt/dagster/dagster_home/entrypoint.sh"]
